/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
import React, { useEffect, useState } from "react";
import Head from "next/head";
import Button from "../../components/Button";
import CardEvent from "../../components/CardEvent";
import Footer from "../../components/Footer";
import Navbar from "../../components/Navbar";
import Statistics from "../../components/Statistics";
import Stories from "../../components/Stories";
import { useRouter } from "next/router";
import { getData } from "../../utils/fetchData";
import moment from "moment";
import { formatDate } from "../../utils/formatDate";
import Cookies from "js-cookie";

export default function DetailPage({ detailPage, id }) {
  const [data, setData] = useState([]);
  const [qtyTicket, setQtyTicket] = useState(1);
  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await getData("api/v1/events");

        setData(res.data);
      } catch (err) {}
    };

    fetchData();
  }, []);

  const router = useRouter();

  const handleSubmit = (ticketId, organizer) => {
    const token = Cookies.get("token");
    if (!token) {
      return router.push("/signin");
    } else {
      router.push(
        `/checkout/${id}?ticketId=${ticketId}&organizer=${organizer}&qtyTicket=${qtyTicket}`
      );
    }
  };

  const handlePlusQty = () => {
    setQtyTicket(qtyTicket + 1);
  };

  const handleMinusQty = () => {
    if (qtyTicket > 1) {
      setQtyTicket(qtyTicket - 1);
    }
  };

  return (
    <>
      <Head>
        <title>Semina || Detail Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="hero-detail bg-navy text-white pb-5">
        <Navbar />
        <div className="container py-5">
          <div className="row align-items-center g-5">
            <div className="col-12 col-lg-7 text-start">
              <span className="badge bg-green text-navy px-3 py-2 rounded-pill fw-bold mb-3">
                {detailPage.category?.name || "Seminar"}
              </span>
              <h1 className="hero-title fw-bold mb-4" style={{ fontSize: "2.8rem", lineHeight: "1.2", color: "white" }}>
                {detailPage.title}
              </h1>
              <div className="d-flex flex-wrap gap-4 text-white-50 fs-6">
                <div className="d-flex align-items-center gap-2">
                  <img src="/icons/ic-calendar.svg" alt="date" width="20" style={{ filter: "brightness(0) invert(1)" }} />
                  <span>{formatDate(detailPage.date)}</span>
                </div>
                <div className="d-flex align-items-center gap-2">
                  <img src="/icons/ic-time.svg" alt="time" width="20" style={{ filter: "brightness(0) invert(1)" }} />
                  <span>{moment(detailPage.date).format("hh:mm A")}</span>
                </div>
                <div className="d-flex align-items-center gap-2">
                  <img src="/icons/ic-marker.svg" alt="venue" width="20" style={{ filter: "brightness(0) invert(1)" }} />
                  <span>{detailPage.venueName}</span>
                </div>
              </div>
            </div>
            <div className="col-12 col-lg-5 text-center">
              <img
                src={
                  detailPage.image.url?.startsWith("http")
                    ? detailPage.image.url
                    : `${process.env.NEXT_PUBLIC_API}/${
                        detailPage.image.url || detailPage.image.name
                      }`
                }
                className="img-fluid shadow-lg event-poster"
                alt="semina"
                style={{ maxHeight: "380px", objectFit: "cover", width: "100%", borderRadius: "24px" }}
              />
            </div>
          </div>
        </div>
      </div>

      <div className="details-content container py-5">
        <div className="d-flex flex-wrap justify-content-lg-center gap">
          <div className="d-flex flex-column description">
            <div className="event-details">
              <h6>Event Details</h6>
              <p className="details-paragraph">{detailPage.about}</p>
            </div>
            <div className="keypoints">
              {detailPage.keyPoint.map((key, i) => {
                return (
                  <div className="d-flex align-items-start gap-3" key={i}>
                    <img src="/icons/ic-check.svg" alt="semina" />
                    <span>{key}</span>
                  </div>
                );
              })}
            </div>
            <div className="map-location">
              <h6>Event Location</h6>
              <div className="map-placeholder">
                <div className="maps">
                  <img src="/images/maps.png" alt="" />
                  <div
                    className="absolute d-flex justify-content-center align-items-center"
                    id="hoverMe"
                  >
                    <a href="#" className="btn-navy" id="btn-maps">
                      View in Google Maps
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="d-flex flex-column card-event">
            <h6>Your Speaker</h6>
            <div className="d-flex align-items-center gap-3 mt-3">
              <img
                src={
                  detailPage?.talent?.image?.url?.startsWith("http")
                    ? detailPage.talent.image.url
                    : `${process.env.NEXT_PUBLIC_API}/${
                        detailPage?.talent?.image?.url ||
                        detailPage?.talent?.image?.name
                      }`
                }
                alt="semina"
                width="60"
              />
              <div>
                <div className="speaker-name">{detailPage?.talent?.name}</div>
                <span className="occupation">{detailPage?.talent?.role}</span>
              </div>
            </div>
            
            <hr />

            <h6>Get Ticket</h6>
            <div 
              className="d-flex gap-4 mt-3 pb-4 ticket-slider" 
              style={{ 
                overflowX: "auto", 
                scrollSnapType: "x mandatory", 
                WebkitOverflowScrolling: "touch",
                paddingRight: "15px",
                paddingLeft: "5px",
                marginRight: "-15px"
              }}
            >
              <style jsx>{`
                .ticket-slider::-webkit-scrollbar {
                  height: 6px;
                }
                .ticket-slider::-webkit-scrollbar-track {
                  background: #f1f1f1; 
                  border-radius: 10px;
                }
                .ticket-slider::-webkit-scrollbar-thumb {
                  background: #c1c1c1; 
                  border-radius: 10px;
                }
                .ticket-slider::-webkit-scrollbar-thumb:hover {
                  background: #a8a8a8; 
                }
                .ticket-card-modern {
                  transition: all 0.3s ease;
                  border: 1px solid #eaeaea;
                }
                .ticket-card-modern:hover {
                  transform: translateY(-5px);
                  box-shadow: 0 10px 20px rgba(0,0,0,0.08) !important;
                }
              `}</style>
              {detailPage.tickets.map((ticket, index) => (
                <div key={index} style={{ scrollSnapAlign: "start", minWidth: "300px" }}>
                  {ticket.statusTicketCategories ? (
                    <div className="ticket-card-modern p-4 rounded-4 shadow-sm bg-white">
                      <div className="d-flex justify-content-between align-items-center mb-3">
                        <div className="fw-bold fs-5 text-dark">{ticket.type}</div>
                        <div className="badge bg-light text-primary border border-primary px-3 py-2 rounded-pill">
                          Available
                        </div>
                      </div>
                      <div className="price mb-4 text-primary">
                        <div className="d-flex justify-content-between align-items-center">
                          <div className="fs-3 fw-bold" style={{ color: '#10193E' }}>
                            {ticket.price === 0 ? "Free" : `$${ticket.price}`}
                          </div>
                          <div className="d-flex align-items-center border rounded-pill bg-light shadow-sm px-2 py-1">
                            <button
                              className="btn btn-sm btn-light rounded-circle fw-bold d-flex align-items-center justify-content-center"
                              style={{ width: "30px", height: "30px", background: 'white' }}
                              onClick={handleMinusQty}
                            >
                              -
                            </button>
                            <div className="fw-bold px-3 text-dark">
                              {qtyTicket}
                            </div>
                            <button
                              className="btn btn-sm btn-light rounded-circle fw-bold d-flex align-items-center justify-content-center"
                              style={{ width: "30px", height: "30px", background: 'white' }}
                              onClick={handlePlusQty}
                            >
                              +
                            </button>
                          </div>
                        </div>
                      </div>
                      
                      <div className="d-flex flex-column gap-2 mb-4">
                        <div className="d-flex gap-3 align-items-center text-secondary">
                          <img src="/icons/ic-marker.svg" alt="venue" width="20" />
                          <span className="fw-medium text-truncate">{detailPage.venueName}</span>
                        </div>
                        <div className="d-flex gap-3 align-items-center text-secondary">
                          <img src="/icons/ic-time.svg" alt="time" width="20" />
                          <span className="fw-medium">{moment(detailPage.date).format("hh:mm A")}</span>
                        </div>
                        <div className="d-flex gap-3 align-items-center text-secondary">
                          <img src="/icons/ic-calendar.svg" alt="date" width="20" />
                          <span className="fw-medium">{formatDate(detailPage.date)}</span>
                        </div>
                      </div>

                      {detailPage.stock !== 0 && (
                        <div className="d-grid mt-3">
                          <Button
                            variant={"btn-green"}
                            action={() =>
                              handleSubmit(ticket._id, detailPage.organizer)
                            }
                          >
                            Join Now
                          </Button>
                        </div>
                      )}
                    </div>
                  ) : (
                    ""
                  )}
                </div>
              ))}
            </div>
            </div>
          </div>
        </div>

      <CardEvent data={data} title="Similiar Events" subTitle="Next One" />
      <Stories />
      <Statistics />
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  const req = await getData(`api/v1/events/${context.params.id}`);

  const res = req.data;

  return {
    props: { detailPage: res, id: context.params.id },
  };
}
