export const START_FETCHING_PARTICIPANTS =
  "redux/talents/START_FETCHING_PARTICIPANTS";
export const SUCCESS_FETCHING_PARTICIPANTS =
  "redux/talents/SUCCESS_FETCHING_PARTICIPANTS";
export const ERROR_FETCHING_PARTICIPANTS =
  "redux/talents/ERROR_FETCHING_PARTICIPANTS";
export const SET_KEYWORD = "redux/talents/SET_KEYWORD";
